services:
  dev-db:
    container_name: dev-db
    image: 'mysql:latest'
    restart: always
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    networks:
      - backend
  product:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - dev-db
    networks:
      - backend

networks:
  backend: