services:
  dev-db:
    container_name: dev-db
    image: 'mysql:latest'
    restart: always
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=verysecret --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - backend
  product:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      dev-db:
        condition: service_healthy
    networks:
      - backend

networks:
  backend: