apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30000
  selector:
    app: product
